/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { Suspense, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";
import { useCategories } from "../store";
import Asset from "./Asset";

export function Avatar({ props }: { props?: THREE.Group }) {
  const group = useRef<THREE.Group>(null);
  const { nodes } = useGLTF("/Armature.glb");

  const customization = useCategories((s) => s.customization);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          {customization.map((c, i) => (
            <Suspense key={c.model + i}>
              <Asset url={c.model} skeleton={nodes.Plane.skeleton} />
            </Suspense>
          ))}
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Armature.glb");
